# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routes_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'routes_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14routes_service.proto\x1a\x1bgoogle/protobuf/empty.proto\"[\n\x0f\x41\x64\x64RouteRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x13\n\x0broute_start\x18\x02 \x01(\t\x12\x11\n\troute_end\x18\x03 \x01(\t\x12\x10\n\x08stop_ids\x18\x04 \x03(\x05\"4\n\x16RouteOperationResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"Q\n\x05Route\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x13\n\x0broute_start\x18\x02 \x01(\t\x12\x11\n\troute_end\x18\x03 \x01(\t\x12\x10\n\x08stop_ids\x18\x04 \x03(\x05\"+\n\x11RouteListResponse\x12\x16\n\x06routes\x18\x01 \x03(\x0b\x32\x06.Route2y\n\x06Routes\x12\x35\n\x08\x41\x64\x64Route\x12\x10.AddRouteRequest\x1a\x17.RouteOperationResponse\x12\x38\n\nListRoutes\x12\x16.google.protobuf.Empty\x1a\x12.RouteListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routes_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDROUTEREQUEST']._serialized_start=53
  _globals['_ADDROUTEREQUEST']._serialized_end=144
  _globals['_ROUTEOPERATIONRESPONSE']._serialized_start=146
  _globals['_ROUTEOPERATIONRESPONSE']._serialized_end=198
  _globals['_ROUTE']._serialized_start=200
  _globals['_ROUTE']._serialized_end=281
  _globals['_ROUTELISTRESPONSE']._serialized_start=283
  _globals['_ROUTELISTRESPONSE']._serialized_end=326
  _globals['_ROUTES']._serialized_start=328
  _globals['_ROUTES']._serialized_end=449
# @@protoc_insertion_point(module_scope)
