JWT_SIGN_KEY = "test_dev_key_1.1"
JWT_ALG = "HS256"


ROUTE_SERVICE_PORT = "5002"
STOP_SERVICE_PORT = "5000"
ROUTES_SERVICE_HOST = f"localhost:{ROUTE_SERVICE_PORT}"
STOP_SERVICE_HOST = f"localhost:{STOP_SERVICE_PORT}"