syntax = "proto3";
import "google/protobuf/empty.proto";

message AddRouteRequest{
    int32 number = 1;
    string route_start = 2;
    string route_end = 3;
    repeated int32 stop_ids = 4;
}

message RouteOperationResponse{
    bool error = 1;
    string msg = 2;
}

message Route{
    int32 number = 1;
    string route_start = 2;
    string route_end = 3;
    repeated int32 stop_ids = 4;
}
message RouteListResponse{
    repeated Route routes = 1;
}

service Routes{
    rpc AddRoute(AddRouteRequest) returns (RouteOperationResponse);
    rpc ListRoutes(google.protobuf.Empty) returns (RouteListResponse);
}
