syntax = "proto3";

// Add Messages
message AddStopRequest{
    string name = 1;
}

// For general operation Messages
message OperationResponse{
    bool success = 1;
    int32 stop_id = 2;
}
message StopIdRequest{
    int32 stop_id = 1;
}
message StopNameResponse{
    string name = 1;
}

// To comfortably work with a list of stops
message StopIdListRequest{
    repeated int32 stop_ids = 1;
}
message StopNameListResponse{
    repeated string names = 1;
}

service Stops{
    rpc AddStop(AddStopRequest) returns (OperationResponse);
    rpc GetStop(StopIdRequest) returns (StopNameResponse);
    rpc UpdateStop(StopIdRequest) returns (OperationResponse);
    rpc DeleteStop(StopIdRequest) returns (OperationResponse);
    rpc TransformStops(StopIdListRequest) returns (StopNameListResponse);
}