# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stops.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'stops.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstops.proto\"\x1e\n\x0e\x41\x64\x64StopRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"5\n\x11OperationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07stop_id\x18\x02 \x01(\x05\" \n\rStopIdRequest\x12\x0f\n\x07stop_id\x18\x01 \x01(\x05\" \n\x10StopNameResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\"%\n\x11StopIdListRequest\x12\x10\n\x08stop_ids\x18\x01 \x03(\x05\"%\n\x14StopNameListResponse\x12\r\n\x05names\x18\x01 \x03(\t2\x86\x02\n\x05Stops\x12.\n\x07\x41\x64\x64Stop\x12\x0f.AddStopRequest\x1a\x12.OperationResponse\x12,\n\x07GetStop\x12\x0e.StopIdRequest\x1a\x11.StopNameResponse\x12\x30\n\nUpdateStop\x12\x0e.StopIdRequest\x1a\x12.OperationResponse\x12\x30\n\nDeleteStop\x12\x0e.StopIdRequest\x1a\x12.OperationResponse\x12;\n\x0eTransformStops\x12\x12.StopIdListRequest\x1a\x15.StopNameListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stops_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDSTOPREQUEST']._serialized_start=15
  _globals['_ADDSTOPREQUEST']._serialized_end=45
  _globals['_OPERATIONRESPONSE']._serialized_start=47
  _globals['_OPERATIONRESPONSE']._serialized_end=100
  _globals['_STOPIDREQUEST']._serialized_start=102
  _globals['_STOPIDREQUEST']._serialized_end=134
  _globals['_STOPNAMERESPONSE']._serialized_start=136
  _globals['_STOPNAMERESPONSE']._serialized_end=168
  _globals['_STOPIDLISTREQUEST']._serialized_start=170
  _globals['_STOPIDLISTREQUEST']._serialized_end=207
  _globals['_STOPNAMELISTRESPONSE']._serialized_start=209
  _globals['_STOPNAMELISTRESPONSE']._serialized_end=246
  _globals['_STOPS']._serialized_start=249
  _globals['_STOPS']._serialized_end=511
# @@protoc_insertion_point(module_scope)
