# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import stops_pb2 as stops__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stops_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StopsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddStop = channel.unary_unary(
                '/Stops/AddStop',
                request_serializer=stops__pb2.AddStopRequest.SerializeToString,
                response_deserializer=stops__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.GetStop = channel.unary_unary(
                '/Stops/GetStop',
                request_serializer=stops__pb2.StopIdRequest.SerializeToString,
                response_deserializer=stops__pb2.StopNameResponse.FromString,
                _registered_method=True)
        self.UpdateStop = channel.unary_unary(
                '/Stops/UpdateStop',
                request_serializer=stops__pb2.StopIdRequest.SerializeToString,
                response_deserializer=stops__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.DeleteStop = channel.unary_unary(
                '/Stops/DeleteStop',
                request_serializer=stops__pb2.StopIdRequest.SerializeToString,
                response_deserializer=stops__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.TransformStops = channel.unary_unary(
                '/Stops/TransformStops',
                request_serializer=stops__pb2.StopIdListRequest.SerializeToString,
                response_deserializer=stops__pb2.StopNameListResponse.FromString,
                _registered_method=True)


class StopsServicer:
    """Missing associated documentation comment in .proto file."""

    def AddStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransformStops(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StopsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddStop': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStop,
                    request_deserializer=stops__pb2.AddStopRequest.FromString,
                    response_serializer=stops__pb2.OperationResponse.SerializeToString,
            ),
            'GetStop': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStop,
                    request_deserializer=stops__pb2.StopIdRequest.FromString,
                    response_serializer=stops__pb2.StopNameResponse.SerializeToString,
            ),
            'UpdateStop': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStop,
                    request_deserializer=stops__pb2.StopIdRequest.FromString,
                    response_serializer=stops__pb2.OperationResponse.SerializeToString,
            ),
            'DeleteStop': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteStop,
                    request_deserializer=stops__pb2.StopIdRequest.FromString,
                    response_serializer=stops__pb2.OperationResponse.SerializeToString,
            ),
            'TransformStops': grpc.unary_unary_rpc_method_handler(
                    servicer.TransformStops,
                    request_deserializer=stops__pb2.StopIdListRequest.FromString,
                    response_serializer=stops__pb2.StopNameListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Stops', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Stops', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Stops:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Stops/AddStop',
            stops__pb2.AddStopRequest.SerializeToString,
            stops__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Stops/GetStop',
            stops__pb2.StopIdRequest.SerializeToString,
            stops__pb2.StopNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Stops/UpdateStop',
            stops__pb2.StopIdRequest.SerializeToString,
            stops__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Stops/DeleteStop',
            stops__pb2.StopIdRequest.SerializeToString,
            stops__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransformStops(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Stops/TransformStops',
            stops__pb2.StopIdListRequest.SerializeToString,
            stops__pb2.StopNameListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
